steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/znayka:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/znayka:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/znayka:$COMMIT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/znayka:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/znayka:latest'

timeout: '1800s'
